FROM python:3.11-slim-bullseye

# 使用阿里云镜像加速
RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list

WORKDIR /opt/vue-fastapi-admin

# 安装 Node.js 和 pnpm
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    gcc python3-dev bash curl gnupg \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && corepack enable \
    && corepack prepare pnpm@9.15.9 --activate \
    && pnpm config set registry https://registry.npmmirror.com \
    && rm -rf /var/lib/apt/lists/*

# 复制依赖文件并安装
COPY requirements.txt .
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# 复制配置文件
COPY deploy/entrypoint-dev.sh .
RUN chmod +x entrypoint-dev.sh

ENV LANG=zh_CN.UTF-8
EXPOSE 9999 3100

ENTRYPOINT [ "sh", "entrypoint-dev.sh" ]
